# Generated by Django 4.0.8 on 2026-06-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], max_length=25)),
                ('year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('auto_allot', models.BooleanField(default=True, help_text='Automatically enroll new matching students into these subjects.')),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(related_name='packages', to='course.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='course.program')),
            ],
            options={
                'ordering': ('program__title', 'level', 'year', 'name'),
            },
        ),
    ]
