# Generated by Django 5.2.8 on 2025-11-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="relation_ship",
            field=models.CharField(
                choices=[
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Brother", "Brother"),
                    ("Sister", "Sister"),
                    ("Grand Mother", "Grand Mother"),
                    ("Grand Father", "Grand Father"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to="profile_pictures/%y/%m/%d/",
            ),
        ),
    ]
