# Generated by Django 5.2.8 on 2025-11-27 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_parent_relation_ship_alter_user_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                help_text="Enter a valid email address",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Enter phone number in format: +1234567890 or (123) 456-7890",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number. Examples: +1234567890, (123) 456-7890, 123-456-7890",
                        regex="^(\\+\\d{1,3}[-.\\s]?)?\\(?\\d{1,4}\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
                    )
                ],
            ),
        ),
    ]
